baseURL: https://anubhavp.dev/cbrtl

title: cbrtl
paginate: 7
theme: papermodx

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/false
          weight: 10


outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "A foundry for programmers who like making stufff :)"
  author: Srijan Paul 

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  # comments: false
  images: ["papermod-cover.png", "assets/icon.ico"]

  profileMode:
    enabled: false
    title: cbrtl
    subtitle: A foundry for programmers
    imageUrl: "https://avatars.githubusercontent.com/u/84934672?s=400&u=2dcad8144be1e67691c4bc7423ff87d1148d06cb&v=4"
    imageTitle: cbrtl
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "cbrtl"
    Content: >
      cbrtl is a small, tight knit group of programmers and open source sorcerers who like 
      to craft fun projects together and build a community. We are a group of developers.  
      
      We are primarily a [GitHub Organization](https://github.com/cbrtl).

  socialIcons:
    - name: github
      url: "https://github.com/cbrtl"
    - name: discord
      url: "https://discord.gg/3qry3u569v"
    - name: RsS
      url: "index.xml"

  editPost:
    URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # label:
  #     text: "Home"
  #     icon: icon.png
  #     iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  assets:
    favicon: icon.ico
  #     favicon16x16: "<link / abs url>"
    favicon32x32: icon.ico 
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  highlight:
    # guessSyntax: true
    # lineNos: true
    noClasses: true
    style: bw

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
